# Sysbench Test Configuration

# global configuration
global:
  enabled_tests: ["cpu", "memory", "fileio"]

# cpu test configuration
cpu:
  enabled: true
  single_thread: 
    enabled: true
    events: 0   #no limit
    time: 30   # 30 seconds
    threads: 1
  multi_thread:   # multi-thread test
    enabled: true
    events: 0
    time: 30
    threads: "auto"  # auto means using CPU cores

# memory test configuration
memory:
  enabled: true
  threads: 4
  time: 30
  block_size: "1K"
  total_size: "100G"

# fileio test configuration
fileio:
  enabled: true
  file_total_size: "1G"
  file_num: 1
  threads: 1
  time: 60
  modes:  # test modes
    - name: "rndrw"
      enabled: true
  cleanup: true  # whether to clean up files after tests

# network test configuration
network:
  enabled: false  # 默认关闭，需要配置服务器IP才能使用
  server_ip: ""   # 设置iperf3服务器IP地址
  time: 10        # 测试时间（秒）
  port: 5201      # iperf3默认端口
